version: '3.4'

services:
  program:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: always
  db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: hello
      POSTGRES_PASSWORD: local
    volumes:
      - ./data:/var/lib/postgresql/data
