version: '3.4'

services:
  program:
    build:
      context: .
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hello
      POSTGRES_PASSWORD: local
    volumes:
      - ./data:/var/lib/postgresql/data
